name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: naresh
  ECR_REPOSITORY: nodeapp

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Test
        run: npm test

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nodeapp-build-files
          path: |
            app.js
            package.json
            Dockerfile
            K8-manifests/  

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip
            pip install semgrep
        
      - name: Verify Semgrep
        run: semgrep --version
        
      - name: Run Semgrep Scan
        run: |
            semgrep scan \
              --config p/security-audit \
              --sarif \
              --output semgrep.sarif

      - name: Snyk Open Source Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} 

      - name: Monitor Project in Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
         command: monitor   

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPOSITORY:${{ github.sha }} .
          docker tag $ECR_REPOSITORY:${{ github.sha }} \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}

      - name: Push Docker Image to ECR
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
          --region $AWS_REGION \
          --name $EKS_CLUSTER_NAME

      - name: Update pod.yml with latest image
        run: |
          sed -i "s|image:.*|image: ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}|g" K8-manifests/pod.yml

      - name: Verify Cluster Access
        run: |
          kubectl config current-context
          kubectl get nodes
          kubectl get pods

      - name: Delete Existing Pod
        run: |
          kubectl delete pod nodeapp-pod --ignore-not-found=true

      - name: Deploy Pod
        run: |
          kubectl apply -f K8-manifests/pod.yml
          kubectl apply -f K8-manifests/service.yml

      - name: Verify Pod
        run: |
          kubectl get pods
          kubectl describe pod nodeapp-pod
